### ISSUE TITLE
Macbook m1 -- does it work?

### ISSUE THREAD

**Issue by maneeshsethi** [rwu823/afloat#61]
I am having trouble getting the bundle to activate on my Apple Silicone Macbook Air M1 (Monterey).

Does Afloat work on M1s?

**Comment by ryan-efendy** [comment]
@maneeshsethi @sidhire @Alexzhanghuan, any of u got it to work in M1 Mac Apple Silicon?

**Comment by grisaitis** [comment]
i'm able to install, but haven't rebooted yet (posting this to edit later)

```
macOS Big Sur
Version 11.5.1

MacBook Pro (13-inch, M1, 2020)
Chip Apple M1
```

```
curl https://raw.githubusercontent.com/rwu823/afloat/master/install.sh | sh

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   482  100   482    0     0    975      0 --:--:-- --:--:-- --:--:--   975
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  540k  100  540k    0     0  1127k      0 --:--:-- --:--:-- --:--:-- 15.4M
Archive:  ./installer-afloat.zip
   creating: Afloat.bundle/
  inflating: SIMBL-0.9.9.pkg         
   creating: Afloat.bundle/Contents/
   creating: Afloat.bundle/Contents/Afloat Scripting.app/
  inflating: Afloat.bundle/Contents/Info.plist  
   creating: Afloat.bundle/Contents/MacOS/
   creating: Afloat.bundle/Contents/Resources/
   creating: Afloat.bundle/Contents/Afloat Scripting.app/Contents/
  inflating: Afloat.bundle/Contents/MacOS/Afloat  
  inflating: Afloat.bundle/Contents/Resources/Afloat2.icns  
  inflating: Afloat.bundle/Contents/Resources/AfloatButton.png  
  inflating: Afloat.bundle/Contents/Resources/AfloatButtonPressed.png  
  inflating: Afloat.bundle/Contents/Resources/AfloatFloatingBadge.png  
  inflating: Afloat.bundle/Contents/Resources/AfloatHUDBackdrop.png  
  inflating: Afloat.bundle/Contents/Resources/AfloatMenuBadge.png  
  inflating: Afloat.bundle/Contents/Resources/AfloatSinkingBadge.png  
   creating: Afloat.bundle/Contents/Resources/en.lproj/
  inflating: Afloat.bundle/Contents/Afloat Scripting.app/Contents/Info.plist  
   creating: Afloat.bundle/Contents/Afloat Scripting.app/Contents/MacOS/
  inflating: Afloat.bundle/Contents/Afloat Scripting.app/Contents/PkgInfo  
   creating: Afloat.bundle/Contents/Afloat Scripting.app/Contents/Resources/
  inflating: Afloat.bundle/Contents/Resources/en.lproj/Afloat.nib  
  inflating: Afloat.bundle/Contents/Resources/en.lproj/AfloatBadge.nib  
  inflating: Afloat.bundle/Contents/Resources/en.lproj/AfloatPanel.nib  
  inflating: Afloat.bundle/Contents/Resources/en.lproj/InfoPlist.strings  
  inflating: Afloat.bundle/Contents/Afloat Scripting.app/Contents/MacOS/Afloat Scripting  
  inflating: Afloat.bundle/Contents/Afloat Scripting.app/Contents/Resources/AfloatScripting.sdef  
   creating: Afloat.bundle/Contents/Afloat Scripting.app/Contents/Resources/English.lproj/
  inflating: Afloat.bundle/Contents/Afloat Scripting.app/Contents/Resources/English.lproj/InfoPlist.strings  
  inflating: Afloat.bundle/Contents/Afloat Scripting.app/Contents/Resources/English.lproj/MainMenu.nib  
Password:
installer: Package name is SIMBL
installer: Installing at base path /
installer: Preparing for installation….....
installer: Preparing the disk….....
installer: Preparing SIMBL….....
installer: Waiting for other installations to complete….....
installer: Configuring the installation….....
installer: 
#
installer: Running package scripts….....
installer: Validating packages….....
#
installer:      Running installer actions…
installer: 
installer: Finishing the Installation….....
installer: 
#
installer: The software was successfully installed......
installer: The install was successful.
```
